version: "3"

services:
  app:
    image: node:21.7.3-bullseye
    working_dir: /workspace
    command: |
      /bin/bash -c "
        apt-get update &&
        apt-get install -y postgresql-client iputils-ping &&
        sleep infinity
      "
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
