name: Create branch on issue labeled

on:
  issues:
    types: [labeled]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create branch for issue
        uses: peterjgrainger/action-create-branch@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: issue/${{ github.event.issue.number }}