name: Create PR on Push

on:
  push:
    branches-ignore:
      - 'main'
      - 'release'

jobs:
  create-pr:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Get branch name
        id: branch-name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Check if PR exists
        id: check_pr
        run: |
          pr_exists=$(gh pr list --base main --head ${{ steps.branch-name.outputs.BRANCH_NAME }} --json number --jq 'length')
          echo "PR_EXISTS=$pr_exists" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Create PR
        if: steps.check_pr.outputs.PR_EXISTS == '0'
        run: |
          gh pr create --base main --head ${{ steps.branch-name.outputs.BRANCH_NAME }} --title "Automated PR from ${{ steps.branch-name.outputs.BRANCH_NAME }} to main" --body "This is an automated PR created by GitHub Actions."
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
